aws_core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path("users/",include('AWSUser.urls')),
    path('events/',include('event.urls')),
    path('blogs/',include('blog.urls')),
    path('teams/',include('teams.urls')),
    path('gallery/',include('gallery.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
handler404 = 'home.views.custom_404'

blog/urls.py
from django.urls import path
from .views import BlogList,BlogDetail
app_name='blog'
urlpatterns = [
    path('',BlogList.as_view(),name='bloglist'),
    path('view/<int:id>',BlogDetail.as_view(),name='blogdetail'),
]

event/urls.py
from django.urls import path
from .views import EventDetail,EventList,GrandEvent
app_name='event'
urlpatterns = [
    path('',EventList.as_view(),name="EventList"),
    path('view/<int:id>',EventDetail.as_view(),name="EventDetail"),
    path('grand/<int:id>',GrandEvent.as_view(),name="GrandEvent")
]

home/urls.py
from django.urls import path
from .views import HomeView,AboutUs

app_name="home"
urlpatterns = [
    path('',HomeView.as_view(),name="home"),
    path('aboutus/',AboutUs.as_view(),name="aboutus")
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.views import View
from event.models import GrandEventSystem,EventSystem
from blog.models import AWSBlog
from django.utils import timezone
from datetime import datetime
class HomeView(View):

    def get(self,request):
        latest_events = EventSystem.objects.order_by('-startDate')[:3]
        latest_blogs=AWSBlog.objects.order_by('-date_of_publish')[:3]
        current_time = timezone.now()
        current_time=current_time.replace(hour=0, minute=0, second=0)
        grand_event = GrandEventSystem.objects.filter(EventStatus='Ongoing',startDate__gt=current_time).order_by('startDate').first()
        context={
            'events':latest_events,
            'blogs':latest_blogs,
            'grand_event':grand_event
        }
        return render(request,'home/homepage.html',context)
    
def custom_404(request, exception):
    return render(request, "home/404.html")

class AboutUs(View):
    def get(self,request):
        return render(request,'home/aboutus.html')

home/templates/home/aboutus.html
{% extends "base.html" %}
{% block title %}About Us{% endblock %}
{% block content %}
<header class="text-white text-center py-12">
    <h1 class="text-4xl font-bold mt-16">About Us</h1>
  </header>

  <section class="text-center py-12 px-4">
    <h2 class="text-2xl text-gray-400 font-bold">Mission And Values</h2>
    <p class=" text-gray-400 mt-4 max-w-2xl mx-auto">
      The AWS Cloud Club aims to empower students and technology enthusiasts by providing comprehensive learning opportunities and hands-on experiences with AWS cloud technologies. We foster a supportive community for collaboration and innovation, encouraging members to solve real-world problems and make a positive impact. Our club also focuses on career development by offering networking, mentorship, and guidance to help members succeed in cloud computing and related fields.
    </p>
    <div class="flex justify-center space-x-8 mt-8 animate-fadeIn">
      <div class="transition transform hover:scale-110">
        <h3 class="text-4xl font-bold text-white" >100+</h3>
        <p class="text-gray-400">Members</p>
      </div>
      <div class="transition transform hover:scale-110">
        <h3 class="text-4xl font-bold text-white" >30+</h3>
        <p class="text-gray-400 ">Events organized</p>
      </div>
      <div class="transition transform hover:scale-110">
        <h3 class="text-4xl font-bold text-white" >80+</h3>
        <p class="text-gray-400">Community Partnership</p>
      </div>
    </div>
  </section>

  <section class="bg-gradient-to-r from-purple-800 text-white py-12 px-4">
    <h2 class="text-2xl font-bold text-center">Our Vision</h2>
    <p class="mt-4 text-center max-w-2xl mx-auto">

Our vision is to become a leading community that inspires and equips the next generation of cloud professionals to innovate and transform the world through cloud technology. We aspire to create an inclusive and dynamic environment where members can explore cutting-edge solutions, collaborate on impactful projects, and achieve excellence in their cloud computing careers. By nurturing talent and fostering creativity, we aim to drive technological advancements that contribute to a more connected and sustainable future.
    </p>
  </section>

  <section class="text-center py-12 px-4">
    <h2 class="text-2xl font-bold">Our Specialties</h2>
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-8 mt-8">
      <div class=" bg-gradient-to-r from-purple-800 p-4 shadow-lg rounded-lg hover:bg-orange-600">
        <h3 class="text-xl text-white font-bold">Project Based Learning </h3>
      </div>
      <div class=" bg-gradient-to-r from-purple-800 p-4 shadow-lg rounded-lg hover:bg-orange-600">
        <h3 class="text-xl text-white font-bold">Seminars </h3>
      </div>
      <div class=" bg-gradient-to-r from-purple-800 p-4 shadow-lg rounded-lg hover:bg-orange-600">
        <h3 class="text-xl text-white font-bold">Cloud Advocacy </h3>
      </div>
      <div class=" bg-gradient-to-r from-purple-800 p-4 shadow-lg rounded-lg hover:bg-orange-600">
        <h3 class="text-xl text-white font-bold">Guest Speaker </h3>
      </div>
      <div class=" bg-gradient-to-r from-purple-800 p-4 shadow-lg rounded-lg hover:bg-orange-600">
        <h3 class="text-xl text-white font-bold">Certification support</h3>
      </div>
      <div class=" bg-gradient-to-r from-purple-800 p-4 shadow-lg rounded-lg hover:bg-orange-600">
        <h3 class="text-xl text-white font-bold">Fellowship </h3>
      </div>
      <div class=" bg-gradient-to-r from-purple-800 p-4 shadow-lg rounded-lg hover:bg-orange-600">
        <h3 class="text-xl text-white font-bold">Competitions</h3>
      </div>
    
    </div>
  </section>

  <section class=" bg-gradient-to-r from-purple-800  py-12 px-4 rounded-lg">
    <h2 class="text-2xl font-bold text-center">Our Objectives</h2>
    <div class="grid grid-cols-1 md:grid-cols-2 gap-8 mt-8 max-w-5xl mx-auto">
      <div class="p-4 shadow-lg rounded-lg bg-white hover:shadow-xl transition-shadow">
        <h3 class="text-xl font-bold">Awarness</h3>
        <p class="text-gray-700 mt-2">To educate and aware students on AWS cloud technologies and services.</p>
      </div>
      <div class="p-4 shadow-lg rounded-lg bg-white hover:shadow-xl transition-shadow">
        <h3 class="text-xl font-bold">Training</h3>
        <p class="text-gray-700 mt-2">To offer practical, hands-on experience through club events, projects, and initiatives.</p>
      </div>
      <div class="p-4 shadow-lg rounded-lg bg-white hover:shadow-xl transition-shadow">
        <h3 class="text-xl font-bold">Certification Support</h3>
        <p class="text-gray-700 mt-2">⁠⁠To support students in achieving AWS certification.</p>
      </div>
      <div class="p-4 shadow-lg rounded-lg bg-white hover:shadow-xl transition-shadow">
        <h3 class="text-xl font-bold">Networking</h3>
        <p class="text-gray-700 mt-2">To facilitate networking opportunities with AWS community leaders, enthusiasts, students, and professionals, keeping us updated on AWS innovations</p>
      </div>
    </div>
  </section>

  <section class=" text-white text-center py-12 px-4 my-16">
    <h2 class="text-2xl font-bold">Testimonials</h2>
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8 mt-8 max-w-5xl mx-auto">
      <div class="p-4 shadow-lg rounded-lg bg-gradient-to-r from-purple-800 hover:bg-green-500 transition-colors">
        <p>"AWS Cloud Club Nepal has been a game-changer for me. The supportive community and hands-on workshops have boosted my skills and career prospects. I've gained practical experience and made valuable connections."</p>
        <h3 class="mt-4 font-bold"> Rajendra Acharya</h3>
      </div>
      <div class="p-4 shadow-lg rounded-lg bg-gradient-to-r from-purple-800 hover:bg-green-500 transition-colors">
        <p>"Joining AWS Cloud Club Nepal was a great decision. The events are insightful, combining technical learning with networking. I've deepened my AWS knowledge and found inspiration to pursue my tech passion."</p>
        <h3 class="mt-4 font-bold">Akrur Neupane</h3>
      </div>
      <div class="p-4 shadow-lg rounded-lg bg-gradient-to-r from-purple-800 hover:bg-green-500 transition-colors">
        <p>"Being a member of AWS Cloud Club Nepal has expanded my understanding of AWS and opened career opportunities. The collaborative community fosters personal and professional growth."</p>
        <h3 class="mt-4 font-bold"> Prerana Blown Lama</h3>
      </div>
   
    </div>
  </section>

  <section class="text-center py-12 px-4 w-full">
      <h2 class="text-2xl font-bold">Get Answer To Your Most Asked Questions</h2>
    
      <div class="mt-8">
        <div class="p-4 border rounded-lg shadow-md transition transform hover:scale-100 scale-90">
          <h3 class="text-xl font-bold">What is the AWS Cloud Club in Nepal?</h3>
          <p class="mt-2 text-gray-400">The AWS Cloud Club in Nepal is a community-driven organization dedicated to educating and empowering students and tech enthusiasts through learning opportunities, hands-on experiences, and networking events centered around AWS cloud computing.</p>
        </div>
      </div>
    
      <div class="mt-8">
        <div class="p-4 border rounded-lg shadow-md transition transform hover:scale-100 scale-90">
          <h3 class="text-xl font-bold">Who can join the AWS Cloud Club in Nepal?</h3>
          <p class="mt-2 text-gray-400">The club is open to all students and technology enthusiasts in Nepal who are interested in exploring AWS cloud technologies, regardless of their experience level.</p>
        </div>
      </div>
    
      <div class="mt-8">
        <div class="p-4 border rounded-lg shadow-md transition transform hover:scale-100 scale-90">
          <h3 class="text-xl font-bold">How do I become a member of the AWS Cloud Club in Nepal?</h3>
          <p class="mt-2 text-gray-400">You can join by attending our events, participating in our activities, and signing up through our online registration form available on the club's website or at our meetings.</p>
        </div>
      </div>
    
      <div class="mt-8">
        <div class="p-4 border rounded-lg shadow-md transition transform hover:scale-100 scale-90">
          <h3 class="text-xl font-bold">What kind of events does the AWS Cloud Club in Nepal organize?</h3>
          <p class="mt-2 text-gray-400">We organize a variety of events, including hands-on workshops, technical talks by industry experts, certification study sessions, and hackathons to foster learning and innovation.</p>
        </div>
      </div>
    
      <div class="mt-8">
        <div class="p-4 border rounded-lg shadow-md transition transform hover:scale-100 scale-90">
          <h3 class="text-xl font-bold">Do I need any prior experience with AWS to join the club?</h3>
          <p class="mt-2 text-gray-400">No prior experience is required. Our events are designed to cater to beginners as well as those with more advanced knowledge of AWS technologies.</p>
        </div>
      </div>
    
      <div class="mt-8">
        <div class="p-4 border rounded-lg shadow-md transition transform hover:scale-100 scale-90">
          <h3 class="text-xl font-bold">How can the club help me with AWS certification?</h3>
          <p class="mt-2 text-gray-400">We provide study groups, access to resources, and mentorship from certified AWS professionals to support members in preparing for AWS certification exams.</p>
        </div>
      </div>
    
      <div class="mt-8">
        <div class="p-4 border rounded-lg shadow-md transition transform hover:scale-100 scale-90">
          <h3 class="text-xl font-bold">Are there any membership fees for the AWS Cloud Club in Nepal?</h3>
          <p class="mt-2 text-gray-400">Membership is free, but some events may have a small fee to cover materials or special guests.</p>
        </div>
      </div>
    
      <div class="mt-8">
        <div class="p-4 border rounded-lg shadow-md transition transform hover:scale-100 scale-90">
          <h3 class="text-xl font-bold">How can I stay updated on club activities and events?</h3>
          <p class="mt-2 text-gray-400">Follow us on our social media platforms, subscribe to our newsletter, and check our website regularly for the latest updates and event information.</p>
        </div>
      </div>
    
      <div class="mt-8">
        <div class="p-4 border rounded-lg shadow-md transition transform hover:scale-100 scale-90">
          <h3 class="text-xl font-bold">Can I suggest topics or speakers for club events?</h3>
          <p class="mt-2 text-gray-400">Yes! We encourage members to share their ideas and suggestions for topics or speakers they would like to see featured in our events.</p>
        </div>
      </div>
    
      <div class="mt-8">
        <div class="p-4 border rounded-lg shadow-md transition transform hover:scale-100 scale-90">
          <h3 class="text-xl font-bold">How can the AWS Cloud Club in Nepal benefit my career?</h3>
          <p class="mt-2 text-gray-400">By joining the club, you'll gain valuable skills, hands-on experience, and networking opportunities with industry professionals, which can enhance your career prospects and open doors to new opportunities.</p>
        </div>
      </div>
    
      <div class="mt-8">
        <div class="p-4 border rounded-lg shadow-md transition transform hover:scale-100 scale-90">
          <h3 class="text-xl font-bold">How do I contact the club for more information?</h3>
          <p class="mt-2 text-gray-400">You can reach us via email at awscloudclub.nepal@gmail.com or connect with us on our social media channels for more information and inquiries.</p>
        </div>
      </div>
    
    </section>
{% endblock %}

home/templates/home/homepage.html
{% extends "base.html" %}
{% block title %}AWS Cloud Club Nepal{% endblock %}
{% load static %}
{% block content %}
<!-- student Community Day -->
<section class="flex justify-center items-center border border-gray-10 my-2 lg:my-15 md:my-8">
    <div class="w-full max-w-screen-lg ">
        <h2 class="my-16 text-4xl font-bold tracking-tight leading-none text-center text-gray-900 md:text-4xl lg:text-4xl dark:text-white">
            <span class="bg-clip-text text-transparent bg-gradient-to-r from-blue-500 to-green-500 animate-gradient-x">
                Grand Event
            </span>
        </h2>
        <div class="mx-auto max-w-screen-xl text-center lg:py-2 lg:px-12 p-4 lg:p-0">
            {% if grand_event %}
            <h1 class="mb-4 text-white text-xl font-extrabold tracking-tight leading-none md:text-xl lg:text-2xl">
                {{grand_event.title}}</h1>
            <div class="px-3">
                <p class="px-5 mx-5 text-gray-500 lg:mb-8 md:text-lg lg:text-xl dark:text-gray-400">
                    {{grand_event.description}}
                </p>
            </div>
            <p class="mb-8 text-lg font-normal text-gray-500 lg:text-xl sm:px-16 xl:px-48 dark:text-gray-400"></p>
            <div class="flex justify-center">
                <div id="countDown" class="flex gap-8 text-center text-white [&>*>h2]:text-xl [&>*>h2]:sm:text-3xl [&>*>h2]:font-bold [&>*>p]:text-sm [&>*>p]:font-semibold">
                    <div>
                        <h2 id="day" class="text-white">{{ grand_event.startDate|date:"d" }}</h2>
                        <p>Days</p>
                    </div>
                    <div>
                        <h2 id="hour" class="text-white">{{ grand_event.startDate|date:"H" }}</h2>
                        <p>Hours</p>
                    </div>
                    <div>
                        <h2 id="minute" class="text-white">{{ grand_event.startDate|date:"i" }}</h2>
                        <p>Minutes</p>
                    </div>
                    <div>
                        <h2 id="second" class="text-white">{{ grand_event.startDate|date:"s" }}</h2>
                        <p>Seconds</p>
                    </div>
                </div>
                <p id="eventToday" class='mt-2 font-bold text-4xl'></p>
            </div>
            <div class="flex flex-col mb-8 lg:mb-16 space-y-4 sm:flex-row sm:justify-center sm:space-y-0 sm:space-x-4">
                <a href="{% url 'event:GrandEvent' grand_event.id %}" class="py-16 my-8 text-white bg-gradient-to-r from-orange-500 via-orange-600 to-red-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-purple-300 dark:focus:ring-purple-800 font-extrabold rounded-lg px-5 py-2.5 text-center me-2 mb-2">
                    Grab your Ticket Now</a>
            </div>
            {% else %}
            <h1 class="mb-4 text-1xl font-extrabold tracking-tight leading-none text-gray-900 md:text-2 xl lg:text-3xl dark:text-white">
                No Upcoming Events</h1>
            {% endif %}
        </div>
    </div>
</section>

<!-- main-section -->
<section class="lg:py-16">
    <div class="grid max-w-screen-xl px-4 py-8 mx-auto lg:gap-8 xl:gap-0 lg:py-16 lg:grid-cols-12">
        <div class="mr-auto place-self-center lg:col-span-7">
            <h1
                class="max-w-2xl mb-4 text-2xl  text-white font-extrabold tracking-tight leading-none md:text-2xl xl:text-4xl dark:text-white">
                AWS Cloud Club in Nepal</h1>
            <h2
                class="mb-4 text-1xl font-normal tracking-tight leading-none text-gray-900 md:text-1xl lg:text-2xl dark:text-white">
                <span
                    class="bg-clip-text text-transparent bg-gradient-to-r from-blue-500 to-green-500 animate-gradient-x">
                    Where Clouds Code, Coffee Flows, and IT Geeks Roam Free!
                </span>
            </h2>
            <p class="max-w-2xl mb-6 font-light text-gray-500 lg:mb-8 md:text-lg lg:text-xl dark:text-gray-400">
                The AWS Cloud Club at Nepal introduces cloud computing, focusing on AWS, to Nepal&apos;s
                education sector. It&apos;s a vibrant community of students exploring and innovating in cloud
                technology, aiming to empower future Nepalese leaders with essential digital skills.</p>
            <a href="/aboutus/"
                class="inline-flex items-center justify-center px-5 py-3 mr-3 text-base font-medium text-center text-white rounded-lg bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 dark:focus:ring-primary-900">
                Explore more
                <svg class="w-5 h-5 ml-2 -mr-1" fill="currentColor" viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg">
                    <path fillRule="evenodd"
                        d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
                        clipRule="evenodd"></path>
                </svg>
            </a>
            {% if not user.is_authenticated %}
            <a href="/users/login/"
                class="inline-flex items-center justify-center px-5 py-3 text-base font-extrabold text-center text-white border border-gray-300 rounded-lg hover:bg-gradient-to-r from-purple-500 via-purple-600 to-purple-700 focus:ring-4 focus:outline-none focus:ring-purple-300 dark:focus:ring-purple-800  me-2 mb-2 ">
                Subscribe us
            </a>
            {% endif %}
        </div>
        <div class="hidden lg:mt-0 lg:col-span-5 lg:flex">
            <img src="{% static "assets/cloud_related/cloudman.png" %}" alt="mockup" class="responsive-img" />
        </div>

    </div>
</section>



<!-- event card -->
<br>
<h2
    class=" my-16  text-4xl font-bold tracking-tight leading-none text-center text-gray-900 md:text-4xl lg:text-4xl dark:text-white">
    <span class="bg-clip-text text-transparent bg-gradient-to-r from-blue-500 to-green-500 animate-gradient-x">
        Events
    </span>
</h2>

<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
    {% if events %}
    {% for event in events %}
    <div
		    class="p-7 bg-transparent border border-gray-200 rounded-lg shadow dark:bg-transparent dark:border-gray-700 gradient-border cursor-pointer hover:bg-gradient-to-r from-purple-500 via-purple-600 to-purple-700 transition-all duration-300 ease-in-out"> 
        <img class="mb-5" src="{{event.image.url}}" alt="{{event.title}}">
        <a href="{% url 'event:EventDetail' event.id %}">
            <h5 class="mb-2 text-2xl font-semibold tracking-tight text-white dark:text-white">{{event.title}}</h5>
        </a>
        <a href="{% url 'event:EventDetail' event.id %}"
                class="inline-flex items-center justify-center px-5 py-3 mr-3 text-base font-medium text-center text-white rounded-lg bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 dark:focus:ring-primary-900">
                Explore more
                <svg class="w-5 h-5 ml-2 -mr-1" fill="currentColor" viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg">
                    <path fillRule="evenodd"
                        d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
                        clipRule="evenodd"></path>
                </svg>
            </a>
    </div>
    {% endfor %}
    {% else %}
    <p class='text-2xl text-center'>No Events available</p>
    {% endif %}
</div>

<!-- Popular Blogs -->
<br>
<h2
    class=" my-16  text-4xl font-bold tracking-tight leading-none text-center text-gray-900 md:text-4xl lg:text-4xl dark:text-white">
    <span class="bg-clip-text text-transparent bg-gradient-to-r from-blue-500 to-green-500 animate-gradient-x">
        Blogs
    </span>
</h2>

<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
    {% if blogs %}
    {% for blog in blogs %}
    <div
        class="p-7 bg-transparent border border-gray-200 rounded-lg shadow dark:bg-transparent dark:border-gray-700 gradient-border cursor-pointer hover:bg-gradient-to-r from-purple-500 via-purple-600 to-purple-700 transition-all duration-300 ease-in-out">
        <img src="{{blog.blog_image.url}}" alt="{{blog.title}}">
        <a href="{% url 'blog:blogdetail' blog.id %}">
            <h5 class="mb-2 text-2xl font-semibold tracking-tight text-white dark:text-white">{{blog.title}}</h5>
        </a>
        <p class="mb-3 font-light text-gray-500 dark:text-white lg:mb-8 md:text-lg lg:text-xl">{{blog.summary|truncatechars:150}}
        </p>
        <a href="{% url 'blog:blogdetail' blog.id %}"
                class="inline-flex items-center justify-center px-5 py-3 mr-3 text-base font-medium text-center text-white rounded-lg bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 dark:focus:ring-primary-900">
                Explore more
                <svg class="w-5 h-5 ml-2 -mr-1" fill="currentColor" viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg">
                    <path fillRule="evenodd"
                        d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
                        clipRule="evenodd"></path>
                </svg>
            </a>
    </div>
    {% endfor %}
    {% else %}
        <p class='text-2xl text-center'>No blogs available</p>
    {% endif %}


</div>
{% endblock %}
{% block scripts %}
 <script>
    var countDownDate = {{grand_event.startDate|date:"U"}} * 1000;
    const daysElement = document.getElementById('day');
    const hoursElement = document.getElementById('hour');
    const minutesElement = document.getElementById('minute');
    const secondsElement = document.getElementById('second');
    var x = setInterval(function () {
        let today = new Date().getTime();
        let interval = countDownDate - today;
        let days = Math.floor(interval / (1000 * 60 * 60 * 24)); // Calculate days
        let hours = Math.floor((interval % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        let minutes = Math.floor((interval % (1000 * 60 * 60)) / (1000 * 60));
        let seconds = Math.floor((interval % (1000 * 60)) / 1000);

        daysElement.innerHTML = days;
        hoursElement.innerHTML = hours;
        minutesElement.innerHTML = minutes;
        secondsElement.innerHTML = seconds;
        if (interval < 0) {
            clearInterval(x);
            document.getElementById("eventToday").innerHTML = "Event Happening Today!!!";
            document.getElementById("countDown").style.display = "none";
        }
    }, 1000);

    function countdownTimer() {
    let countDownDate = new Date('Sep 29, 2024 09:00:00').getTime();

    var x = setInterval(function() {
        var now = new Date().getTime();
        var distance = countDownDate - now;

        var days = Math.floor(distance / (1000 * 60 * 60 * 24));
        var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
        var seconds = Math.floor((distance % (1000 * 60)) / 1000);

        document.getElementById('days').innerHTML = days;
        document.getElementById('hours').innerHTML = hours;
        document.getElementById('minutes').innerHTML = minutes;
        document.getElementById('seconds').innerHTML = seconds;

        if (distance < 0) {
        clearInterval(x);
        document.getElementById('countdown').innerHTML = 'EXPIRED';
        }
        }, 1000);
    }


    countdownTimer();

</script>

{% endblock %}